export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const SET_POSTS_SUCCESS = "SET_POSTS_SUCCESS";
export const SET_POSTS_LOADING = "SET_POSTS_LOADING";
export const SET_POSTS_FAILURE = "SET_POSTS_FAILURE";
